version: "3.9"

services:
  telegram-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-client
    volumes:
      - ./sessions:/app/sessions      # Файл сессии
      - ./logs:/app/logs              # Логи
      - ./data:/app/data              # База SQLite
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - TARGET_CHANNEL=${TARGET_CHANNEL}
      - CHAT_IDS=${CHAT_IDS}
      - KEYWORDS=${KEYWORDS}
      - SEARCH_INTERVAL=${SEARCH_INTERVAL}